apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: app-from-source
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        source:
          git:
            url: https://github.com/bcadiot/hello-go.git
            revision: master
        template:
          name: kaniko
          arguments:
          - name: IMAGE
            value: eu.gcr.io/sandbox-bcadiot/hello-pcd19
          - name: DOCKERFILE
            value: /workspace/Dockerfile
      revisionTemplate:
        spec:
          container:
            image: eu.gcr.io/sandbox-bcadiot/hello-pcd19
            imagePullPolicy: Always
            env:
            - name: "TARGET"
              value: "Source to URL @ PCD 19"