apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: helloworld
  namespace: default
spec:
  template:
    metadata:
      name: helloworld-pcd
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: "TARGET"
              value: "Paris Container Day"